spring.application.name=Food-Project

spring.datasource.url=jdbc:postgresql://localhost:5432/Food_DB
spring.datasource.username=postgres
spring.datasource.password=Supradip@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


jwt.secret = HWGgddib98rybc1X(#R2398ryy623^E*#Qonwhqlffhi